package es.bsc.inb.adestagger.model;

/**
 * Domain of Finding, SEND data model
 * @author jcorvi
 *
 */
public enum Domain {
	BW, BG, CL, DD, FW, LB, MA, MI, OM, PP, TF, VS, EG, CV, RE, BEHAVIORAL_DOMAIN, COMMENTS_DOMAIN, DEMOGRAPHICS_DOMAIN, FM, EXPOSURE_DOMAIN, DISPOSITION_DOMAIN, FERTILITY_DOMAIN, BODY_WEIGHT_DOMAIN, FX, IC, CESARIAN_SECTION_DELIVERY_LITTER_DOMAIN, NERVOUS_SYSTEM_DOMAIN, TRIAL_SETS_DOMAIN, TRIAL_STAGES_DOMAIN, TRIAL_ELEMENTS_DOMAIN, TRIAL_PATHS_DOMAIN, TRIAL_SUMMARY_DOMAIN, TRIAL_ARMS_DOMAIN, SUBJECT_STAGES_DOMAIN, SC, SUBJECT_ELEMENTS_DOMAIN, NONCLINICAL_PREGNANCY_DOMAIN, PHARMACOKINETICS_PARAMETERS_DOMAIN, PALPABLE_MASSES_DOMAIN, PHARMACOKINETIC_CONCENTRATION_DOMAIN, PARING_EVENTS_DOMAIN
}
